CREATE TABLE CATEGORY (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY (NAME) VALUES ('Lazer');
INSERT INTO CATEGORY (NAME) VALUES ('Supermercado');
INSERT INTO CATEGORY (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORY (NAME) VALUES ('Fármacia');
INSERT INTO CATEGORY (NAME) VALUES ('Outros');
